### ISSUE TITLE
Code_01

### ISSUE THREAD

**Issue by JosephThien2000** [JosephThien2000/do_an_lap_trinh_co_ban#1]
+ Nhập xuất thông tin sinh viên
+ Nhập xuất điểm thi cuối kỳ và kết quả xếp loại của sinh viên.
ĐỒ ÁN 1
Một trường đại học quản lý số sinh viên của mình gồm các thông tin: họ tên sinh 
viên, ngày tháng năm sinh, mã số sinh viên.
Giả sử, một học kì sinh viên được học 5 môn, mỗi môn từ 1 đến 3 tín chỉ, tổng số
tín chỉ đăng ký ít nhất là 10 chỉ. Kết thúc học kì, mỗi sinh viên được tính điểm kết thúc 
học phần (70% điểm thi hết môn và 30% điểm thi giữa kì). Nếu đạt 5 điểm trở lên thì qua 
môn
Sau đó, nhà trường tính điểm cuối kì:
(điểm kết thúc học phần x số tín chỉ mỗi môn) / cho tổng số tín chỉ
Sinh viên được xếp loại cuối kì dựa vào điểm cuối kì:
- Nếu điểm cuối kì đạt 9 trở lên xếp loại giỏi
- Nếu điểm cuối kì đạt 7 trở lên xếp loại khá
- Nếu điểm cuối kì đạt 5 trở lên xếp loại trung bình
- Nếu điểm cuối kì dưới 5 xếp loại yếu.
 Yêu cầu:
1. Phân tích dữ liệu sinh viên, xác định kiểu dữ liệu tương ứng
2. Thiết kế lưu đồ khối tổng quát tính điểm cuối kì
Giả sử sinh viên Nguyễn Văn A bao gồm 5 môn 
STT Môn học Điểm 30% Điểm 70%
1 B 5 6
2 C 5 10
3 D 6 1
4 E 7 2
5 F 4 5
Nhập thông tin sinh viên và điểm từ bàn phím 
Xuất ra màn hình các thông tin sau:
- Thông tin sinh viên
- Điểm kết thúc của từng môn học + kết quả (đậu/rớt)
- Điểm trung bình học kì và xếp loại

**Comment by JosephThien2000** [comment]
Hello Hoa

**Comment by JosephThien2000** [comment]
Mình là Thiện nè

**Comment by maihoavo** [comment]
tui là Hoa nè mọi người

**Comment by maihoavo** [comment]
Để mình code nha

**Comment by JosephThien2000** [comment]
Okay Hoa
